### ISSUE TITLE
Laravel 5 

### ISSUE THREAD

**Issue by sirsquall** [mikemand/logviewer#83]
Hi,

Have you plan to create a new release for Laravel 5 ?

**Comment by TresErres** [comment]
+1

**Comment by dinghua** [comment]
+1

**Comment by nayzawoo** [comment]
+1

**Comment by hostianer** [comment]
+1

**Comment by hostianer** [comment]
There`s an Log Viewer L5 Package from this:
https://github.com/rap2hpoutre/laravel-log-viewer

**Comment by mikemand** [comment]
I do not think I will be making this compatible with Laravel 5. The package @hostianer found looks like a worthy successor. I will see if I can help @rap2hpoutre in any way, if he so wishes.

**Comment by GrahamCampbell** [comment]
Also https://github.com/BootstrapCMS/LogViewer.

**Comment by GrahamCampbell** [comment]
Looks like this:

![pryx](https://cloud.githubusercontent.com/assets/2829600/6453231/cf44753c-c133-11e4-851e-3b3d5b5b9181.png)

**Comment by rap2hpoutre** [comment]
@mikemand & @hostianer Thanks :)
@GrahamCampbell haha "Use mine" ;)

**Comment by GrahamCampbell** [comment]
> "Use mine" ;)

Lol ;)
