### ISSUE TITLE
Laravel 5 support please 

### ISSUE THREAD

**Issue by dani3l** [mikemand/logviewer#84]
Hi! I really love that package and it's a shame L5 is not supported 
If you can create a branch with support for L5 that would be awesome! 

thanks

**Comment by arcanedev-maroc** [comment]
@dani3l Try this https://github.com/ARCANEDEV/LogViewer

**Comment by dani3l** [comment]
oh looks nice! I'll try 
thanks

**Comment by arcanedev-maroc** [comment]
:+1: you're welcome

**Comment by mikemand** [comment]
I've been using https://github.com/rap2hpoutre/laravel-log-viewer for L5. ARCANEDEV's looks good too, but has more features than I require for a logviewer.
